const REDACTED = "[已脱敏]";

export function safeDisplay(value: unknown, fallback = "暂无数据"): string {
  const text = typeof value === "string" ? value.trim() : String(value ?? "").trim();

  if (!text) {
    return fallback;
  }

  const lowered = text.toLowerCase();
  const secretMarkers = [
    "authorization:",
    "bearer ",
    "cookie:",
    "set-cookie:",
    "policy_text",
    "secret",
    "token",
    "sk-",
  ];

  if (secretMarkers.some((marker) => lowered.includes(marker))) {
    return REDACTED;
  }

  if (
    /\b(api[_-]?key|password|credential)\b/i.test(text) ||
    /\b(real user data|customer data|production user|live user|personal data|pii)\b/i.test(text) ||
    /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i.test(text) ||
    /\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/.test(text)
  ) {
    return REDACTED;
  }

  return text;
}

export function formatLabel(value: unknown, fallback = "未知"): string {
  const display = safeDisplay(value, fallback);
  const knownLabels: Record<string, string> = {
    access_control: "访问控制",
    access_control_gap_candidate: "访问控制缺口候选",
    access_control_hint: "访问控制提示",
    action: "操作",
    action_failed: "操作失败",
    active_human_lease: "人工租约生效中",
    advisory_memory_only: "仅作建议性记忆",
    advisory_plan_only: "仅作建议性计划",
    advisory_refutation_only: "仅作建议性反证",
    advisory_validation_feedback_only: "仅作建议性验证反馈",
    agent: "智能体",
    agent_run: "智能体运行",
    accepted: "已接受",
    active_hours_closed: "不在允许的活动时段",
    adequate: "充分",
    api_artifact_bundle: "API 资料包",
    api_document: "API 文档",
    api_schema: "API 架构",
    asset_not_authorized: "资产未获授权",
    automated_scanning: "自动扫描",
    browser: "浏览器",
    static: "静态",
    text: "文本",
    ok: "正常",
    approved_validation_record: "已批准的验证记录",
    approval_already_consumed: "审批已使用",
    approval_already_decided: "审批已处理",
    approval_expired: "审批已过期",
    approval_plan_not_active: "计划当前不可审批",
    approved_test_object_id_matrix: "已批准测试对象 ID 矩阵",
    api: "API",
    artifact: "资料",
    artifact_agent: "资料智能体",
    artifact_intake: "资料接入",
    awaiting_evidence_review: "等待证据审核",
    awaiting_human_review: "等待人工审核",
    audit_hash: "审核哈希",
    audit_mode: "审核模式",
    audit_only: "仅审核",
    awaiting_human_approval: "等待人工审核",
    awaiting_approval: "等待审核门",
    awaiting_lease: "等待租约",
    awaiting_review: "等待审核",
    awaiting_review_gate: "等待审核门",
    awaiting_scope_review: "等待范围审核",
    awaiting_validation_review: "等待验证审核",
    baseline: "基准",
    blocked_action: "已阻断操作",
    blocked_by_promotion_audit: "被晋级审核阻断",
    blocked_by_required_evidence: "被必需证据阻断",
    blocked_by_research_feedback: "被研究反馈阻断",
    budget_exhausted: "预算已耗尽",
    brain_memory: "大脑记忆",
    brain_memory_ready: "大脑记忆已就绪",
    browser_workflow_artifact: "浏览器工作流资料",
    boost: "提升",
    candidate: "候选项",
    candidate_evidence_review_required: "候选证据需要审核",
    candidate_not_validated: "候选尚未验证",
    candidate_ready: "候选已就绪",
    candidate_created: "候选已创建",
    campaign: "活动",
    campaign_cycle_review: "活动周期审核",
    campaign_tick: "活动轮次",
    campaign_cycle_review_required: "需要审核活动周期",
    campaign_observation: "活动观察",
    chain_impact: "链路影响",
    claim: "声明",
    claim_text_redacted: "声明文本已脱敏",
    claim_quality: "声明质量",
    claim_review: "声明审核",
    clean: "已清理",
    configured: "已配置",
    code: "代码",
    codebase_map: "代码库映射",
    complete_cycle_review: "完成周期审核",
    completed_cycle_review: "已完成周期审核",
    confirmed_observed_fact: "已确认的观察事实",
    documentation_artifact: "文档资料",
    does_not_confirm_vulnerability: "不确认漏洞",
    drafted: "已起草",
    dispatched: "已分派",
    dry_run: "演练运行",
    dry_run_inline: "内联演练运行",
    duplicate: "重复",
    deduplication: "去重",
    duplicate_risk: "重复风险",
    evidence: "证据",
    evidence_agent: "证据智能体",
    evidence_gap_review_required: "证据缺口需要审核",
    evidence_needed: "需要证据",
    evidence_recorded: "证据已记录",
    evidence_snapshot: "证据快照",
    evidence_quality: "证据质量",
    execution_blocked: "执行已阻断",
    execute_validation: "审核验证审计",
    execution_started: "验证已启动",
    fallback_only: "演示数据",
    fallback_summary: "演示摘要",
    fact: "事实",
    finding: "发现",
    finding_candidate: "漏洞候选",
    finding_promotion: "漏洞候选晋级",
    finding_promotion_blocked: "漏洞候选晋级已阻断",
    finding_promotion_review: "漏洞候选晋级审核",
    gate: "审核门",
    high_signal: "高信号",
    human_gate: "人工审核门",
    human_review: "人工审核",
    human_reviewed: "已人工审核",
    human_review_ready: "人工审核已就绪",
    human_reviewed_gated: "经人工审核受控",
    human_validation_approval: "人工验证批准",
    independent_refutation_or_static_rule: "独立反证或静态规则",
    hypothesis: "假设",
    hypothesis_agent: "假设智能体",
    hypothesis_engine: "假设引擎",
    in_scope: "范围内",
    ingestion: "接入",
    local_files_only: "仅限本地文件",
    local_code_or_har_correlation: "本地代码或 HAR 关联",
    local_static_analysis_only: "仅限本地静态分析",
    learning_signal: "学习信号",
    learning_outcome_recorded: "学习结果已记录",
    limited: "受限",
    manual_observation: "人工观察",
    manual_evidence_recorded: "人工证据已记录",
    manual_preparation: "人工准备",
    manual_result_recorded: "人工结果已记录",
    manual_review_required: "需要人工审核",
    manual_safe_observation: "人工安全观察",
    manual_upload: "人工上传",
    missing_evidence_refs: "缺少证据引用",
    missing_check_refutation_trace: "缺少检查反证轨迹",
    missing_handler_access_control_check: "缺少处理器访问控制检查",
    missing_handler_authz_check: "缺少处理器访问控制检查",
    missing_required_evidence: "缺少必需证据",
    model_claims_unverified: "模型声明未经验证",
    model_reasoning: "模型推理",
    model_reasoning_only: "仅模型推理",
    model_reasoning_not_observed_fact: "模型推理不是观察事实",
    mythos_brain_reasoning_memory: "研究大脑推理记忆",
    normalized: "已规范化",
    mythos_pipeline_autonomous_hunt_queue: "研究流程自动挖掘队列",
    needs_validation_review: "需要验证审核",
    needs_safe_validation_plan: "需要安全验证计划",
    no_auto_submission: "禁止自动提交",
    no_execution_permission: "执行需经人工审核",
    no_live_requests: "禁止实时请求",
    no_path: "无路径",
    no_real_user_data: "禁止真实用户数据",
    no_report_preview: "无报告预览",
    no_scope: "缺少范围",
    not_modeled: "未建模",
    not_reportable: "不可报告",
    non_destructive_validation_only: "仅限非破坏性验证",
    observed_fact: "观察事实",
    observed: "已观察",
    orchestrator_agent: "编排智能体",
    openapi_schema: "OpenAPI 架构",
    openapi: "OpenAPI",
    openapi_promotion_pending: "OpenAPI 晋级待处理",
    optional: "可选",
    out_of_scope: "范围外",
    parked: "已暂停",
    policy: "策略",
    policy_reviewed: "策略已审核",
    pipeline_run: "流程运行",
    projection_unavailable: "投影暂不可用",
    priority: "优先级",
    priority_score: "优先级评分",
    promote_to_finding_candidate: "晋级为漏洞候选",
    preflight: "预检",
    preflight_blocked: "预检已阻断",
    preflight_passed: "预检已通过",
    preflight_required: "需要预检",
    plan: "计划",
    plan_authorization_stale: "计划授权已失效",
    plan_budget_exceeded: "计划超出授权预算",
    plan_step_redacted: "计划步骤已脱敏",
    program: "项目",
    provenance: "溯源",
    queued_review: "已排入审核队列",
    ready_for_human_controlled_validation: "已准备人工受控验证",
    ready_for_manual_promotion: "可进行人工晋级",
    reason: "原因",
    reason_redacted: "原因已脱敏",
    reasoning_memory: "推理记忆",
    redacted: "已脱敏",
    redaction: "脱敏",
    redaction_review: "脱敏审核",
    refutation: "反证",
    refutation_decision: "反证决策",
    refutation_question: "反证问题",
    report_chain_blocked: "报告链已阻断",
    report_chain_review_required: "报告链需要审核",
    report_draft: "报告草稿",
    report_review: "报告审核",
    report_submission_blocked: "报告提交已阻断",
    report_submission: "报告提交",
    report_draft_readiness: "报告草稿就绪度",
    research_audit: "研究审计",
    research_feedback_review: "研究反馈审核",
    research_plan: "研究计划",
    research_queue: "研究队列",
    research_queue_materialized: "研究队列已生成",
    research_task_review_plan: "研究任务审核计划",
    research_task_review: "研究任务审核",
    research_task_refutation_decision: "研究任务反证决策",
    research_task_validation_feedback_review: "研究任务验证反馈审核",
    research_task_validation_feedback: "研究任务验证反馈",
    research_validation_feedback_is_advisory: "研究验证反馈仅作建议性参考",
    request_response_diff: "请求响应差异",
    review_captured: "审核已记录",
    review_gate: "审核门",
    review_required: "需要审核",
    review_ready: "可审核",
    route: "路由",
    route_handler: "路由处理器",
    safe: "安全",
    safe_validation: "安全验证",
    safety_gate: "安全审核门",
    safety_note: "安全说明",
    scanner_run: "扫描运行",
    scope_guard: "范围守卫",
    scope_guard_agent: "范围守卫智能体",
    scope_guard_blocked: "范围守卫已阻断",
    scope_guard_preflight: "范围守卫预检",
    scope_guard_preflight_passed: "范围守卫预检已通过",
    scope_guard_review: "范围守卫审核",
    scope_guard_required: "需要范围守卫审核",
    scope_guard_reviewed: "范围守卫已审核",
    scope_guard_route_approval: "范围守卫路由批准",
    scope_guard_wins: "范围守卫优先",
    same_handler_access_control_evidence: "同处理器访问控制证据",
    same_handler_authz_evidence: "同处理器访问控制证据",
    sensitive_sink: "敏感汇点",
    sensitive_sink_present: "存在敏感汇点",
    sensitive: "敏感",
    source: "来源",
    source_audit: "源代码审计",
    source_fact: "源代码事实",
    stage: "阶段",
    strong: "强",
    submission_blocked_human_review: "报告提交已阻断，需人工审核",
    summarized: "已摘要",
    stopped: "已停止",
    surface: "攻击面",
    summary: "摘要",
    summary_redacted: "摘要已脱敏",
    target_model: "目标模型",
    task: "任务",
    test_accounts_only: "仅限测试账号",
    timeline: "时间线",
    traceable: "可追溯",
    type: "类型",
    unverified_claim: "未验证声明",
    unverified_claim_not_observed_fact: "未验证声明不是观察事实",
    usage: "用途",
    validation: "验证",
    validation_batch: "验证批次",
    validation_agent: "验证智能体",
    validation_feedback: "验证反馈",
    validation_gate: "验证审批门",
    validation_plan: "验证计划",
    validation_plan_ready: "验证计划已就绪",
    validation_planner_agent: "验证规划智能体",
    validation_run: "验证运行",
    validation_manual_result: "人工验证结果",
    two_account_authorization_check: "双账号授权检查",
    validation_step_redacted: "验证步骤已脱敏",
    waiting_for_learning: "等待学习信号",
    waiting_human: "等待人工审核",
    weak: "弱",
    cannot_authorize_execution: "执行仍需人工审核",
    human_approval_required: "需要人工审核",
    human_review_required: "需要人工审核",
    validation_gate_not_approved: "验证需要人工审核",
    unknown: "未知",
    unknown_asset: "未知资产",
    unknown_gate: "未知审核门",
    unknown_scope: "未知范围",
    unknown_sensitivity: "未知敏感度",
    unknown_severity: "未知严重性",
    unknown_status: "未知状态",
    unknown_summary: "未知摘要",
    untitled_campaign: "未命名活动",
    untitled_report_draft: "未命名报告草稿",
    untitled_task: "未命名任务",
    unavailable: "暂不可用",
    none: "无",
    pending: "待处理",
    requested: "已请求",
    awaiting: "等待中",
    waiting: "等待中",
    queued: "排队中",
    running: "运行中",
    active: "进行中",
    complete: "已完成",
    completed: "已完成",
    ready: "就绪",
    approved: "已批准",
    allowed: "已允许",
    allow_finding_promotion: "允许晋级漏洞候选",
    blocked: "已阻断",
    denied: "已拒绝",
    rejected: "已拒绝",
    failed: "失败",
    skipped: "已跳过",
    expired: "已过期",
    revoked: "已撤销",
    consumed: "已消耗",
    used: "已使用",
    missing_scope: "缺少范围",
    needs_review: "需要审核",
    needs_evidence: "需要补充证据",
    not_required: "无需处理",
    not_started: "未开始",
    finished: "已结束",
    passed: "已通过",
    confirmed: "已确认",
    reviewed: "已审核",
    required: "需要处理",
    required_evidence_missing: "缺少必需证据",
    recorded: "已记录",
    not_recorded: "未记录",
    review_only: "仅供审核",
    review_only_no_execution: "仅供审核，不允许执行",
    human_approved_non_destructive_plan: "经人工批准的非破坏性计划",
    needs_human_review: "需要人工审核",
    manual_review: "人工审核",
    authorized_artifacts_only: "仅限授权资料",
    authorized_local_lab: "授权本地实验室",
    local_ai_vulnerability_research_workbench: "本地 AI 漏洞研究工作台",
    needs_more_evidence: "需要更多证据",
    missing_evidence: "缺少证据",
    unverified: "未验证",
    unverified_claim_not_fact: "未验证声明，不是事实",
    report_ready: "报告审核待处理",
    no_verified_evidence_no_high_confidence: "无已验证证据则不得标记高置信度",
    rag_few_shot_context_only_not_cross_validation: "检索与示例仅作上下文，不能交叉验证",
    llm_claims_start_unverified: "模型声明默认未验证",
    scope_imported: "已导入范围",
    fixed_false: "固定为否",
    valid: "有效",
    invalid: "无效",
    not_requested: "未请求",
    relogin_required: "需要重新登录",
    local_lab: "本地实验室",
    disabled_by_default: "默认禁用",
    en: "英语",
    zh: "中文",
    true: "是",
    false: "否",
    submission_blocked: "报告提交已阻断",
    submission_blocked_draft_ready: "提交受阻的报告草稿已就绪",
    locally_validated: "已完成本地验证",
    safely_validated: "已完成安全验证",
    detected: "已发现",
    discovered: "已发现",
    admitted: "已准入",
    unsafe: "不安全",
    high: "高",
    medium: "中",
    low: "低",
    yes: "是",
    no: "否",
    authorization_gap_candidate: "访问控制缺口候选",
    authorization_digest_mismatch: "授权摘要不匹配",
    authorization_missing: "缺少当前授权",
    approval_required_before_validation: "验证前需要人工审核",
    authorization_required: "需要授权",
    awaiting_human_outcome: "等待人工结果",
    blocked_by_research_feedback_gate: "被研究反馈审核门阻断",
    bounded_autonomous_review_only: "仅限受限自主审核",
    candidate_hunter: "候选挖掘",
    candidate_hunter_phase: "候选挖掘阶段",
    candidate_promotion_allowed: "候选晋级已允许",
    create_benchmark_template: "创建基准模板",
    degraded: "降级",
    endpoint: "端点",
    emergency_stop_confirmation_expired: "紧急停止确认已过期",
    emergency_stop_confirmation_invalid: "紧急停止确认无效",
    emergency_stop_confirmation_required: "需要确认紧急停止",
    emergency_stop_confirmation_used: "紧急停止确认已使用",
    autopilot_local_stop_failed: "本地执行上下文撤销失败",
    evidence_review_required: "需要证据审核",
    has_report_safe_evidence: "包含报告安全证据",
    execute_live_validation: "执行实时验证",
    execution_allowed: "执行已允许",
    export_submission_blocked_report: "导出提交已阻断报告",
    fuzzing: "模糊测试",
    har: "HAR",
    healthy: "健康",
    human_approved: "已获人工批准",
    human_submitted: "已由人工提交",
    informative: "信息性结果",
    invalid_lease: "无效租约",
    invalid_response: "响应无效",
    knowledge: "知识",
    learned: "已学习",
    learning_write_allowed: "学习记录写入已允许",
    method: "方法",
    na: "不适用",
    network_error: "网络请求失败",
    not_finished: "未完成",
    object_identifier: "对象标识符",
    plausible: "具有合理性",
    policy_checked: "策略已检查",
    policy_mode_mismatch: "策略模式不匹配",
    promotion_blocked_by_redaction_review: "因脱敏审核阻断晋级",
    provenance_review_required: "需要溯源审核",
    ready_for_human_review: "可进行人工审核",
    redaction_review_required: "需要脱敏审核",
    relationship: "关系",
    recipe_not_authorized: "配方未获授权",
    risk_ceiling_exceeded: "超出风险上限",
    repository_not_allowlisted: "代码仓库不在许可清单中",
    request_failed: "请求失败",
    review_item: "审核项",
    review_top_candidates: "审核高优先级候选",
    role_matrix_observation: "角色矩阵观察",
    run_fuzzer: "运行模糊测试器",
    sarif: "SARIF",
    sbom: "SBOM",
    scope_not_imported: "尚未导入范围",
    scope_snapshot_mismatch: "范围快照不匹配",
    scope_review_required: "需要范围审核",
    semantic_fact: "语义事实",
    sensitive_action: "敏感操作",
    source_audit_blocked: "源代码审计已阻断",
    strategy: "策略说明",
    submit_report: "提交报告",
    validation_allowed: "验证已允许",
    validation_execution_blocked: "验证执行已阻断",
    authorization: "授权信息",
    cookie: "Cookie",
    session: "会话",
    token: "令牌",
  };
  const normalized = display.trim().toLowerCase().replace(/[\s-]+/g, "_");
  const knownLabel = knownLabels[normalized];

  if (knownLabel) {
    return knownLabel;
  }

  const [prefix, ...parts] = display.split(":");
  const prefixLabel = knownLabels[prefix.trim().toLowerCase().replace(/[\s-]+/g, "_")];
  if (
    prefixLabel &&
    parts.length > 0 &&
    parts.every((part) => /^[A-Za-z0-9_-]+$/.test(part.trim()))
  ) {
    return `${prefixLabel}：${parts.map((part) => formatLabel(part)).join("：")}`;
  }

  return display
    .replace(/:/g, ": ")
    .replace(/[_-]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

export function safeStringList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.map((item) => safeDisplay(item)).filter((item) => item !== "暂无数据");
}

export function safeRecordEntries(record: Record<string, unknown> | undefined): [string, string][] {
  if (!record) {
    return [];
  }

  return Object.entries(record).map(([key, value]) => [
    formatLabel(key),
    safeDisplay(typeof value === "string" ? value : JSON.stringify(value)),
  ]);
}
