"""Bounty Autopilot decision contracts and local-lab execution authority.

Phase 1 owns pure, fail-closed authorization, risk, and recipe contracts.
It does not send network traffic, launch browsers, or mutate Campaign state.
"""

from app.bounty_autopilot.asset_admission import (
    AdmissionDecision,
    AssetAdmissionRecord,
    AssetIdentity,
    AssetProvenance,
    NetworkIdentityObservation,
    ScopeMatcher,
    compute_asset_id,
    compute_identity_digest,
    decide_admission,
    is_active_plan_asset_eligible,
    parse_asset_url,
)
from app.bounty_autopilot.branches import (
    BranchBudgetCounters,
    BranchLimits,
    BranchSelection,
    BranchStatus,
    ResearchBranch,
    branch_within_limits,
    select_next_branch,
    transition_branch,
)
from app.bounty_autopilot.candidate_ranking import (
    CandidateImpact,
    CandidateRankingInput,
    CandidateReviewState,
    RankedCandidate,
    rank_candidates,
)
from app.bounty_autopilot.contracts import (
    ACCOUNT_ALIAS_PATTERN,
    AuthorizationBudget,
    CampaignAuthorization,
    CampaignAuthorizationCreate,
    DIGEST_PATTERN,
    MutationInventory,
    PolicyMode,
    RECIPE_ID_PATTERN,
    RecipeRef,
    RiskDecision,
    RiskDecisionStatus,
    RiskTier,
    SafeAlias,
    SCHEMA_VERSION,
    VersionedRecipe,
    canonicalize_authorization_payload,
    compute_authorization_digest,
)
from app.bounty_autopilot.recipes import (
    RECIPE_REGISTRY,
    get_recipe,
    list_recipes,
    resolve_recipe_ref,
)
from app.bounty_autopilot.risk import (
    classify_risk,
    decide_execution_risk,
    evaluate_action_risk,
)

__all__ = [
    "ACCOUNT_ALIAS_PATTERN",
    "AdmissionDecision",
    "AssetAdmissionRecord",
    "AssetIdentity",
    "AssetProvenance",
    "AuthorizationBudget",
    "BranchBudgetCounters",
    "BranchLimits",
    "BranchSelection",
    "BranchStatus",
    "CampaignAuthorization",
    "CampaignAuthorizationCreate",
    "CandidateImpact",
    "CandidateRankingInput",
    "CandidateReviewState",
    "DIGEST_PATTERN",
    "MutationInventory",
    "NetworkIdentityObservation",
    "PolicyMode",
    "RECIPE_ID_PATTERN",
    "RECIPE_REGISTRY",
    "RecipeRef",
    "ResearchBranch",
    "RiskDecision",
    "RiskDecisionStatus",
    "RiskTier",
    "SCHEMA_VERSION",
    "SafeAlias",
    "ScopeMatcher",
    "RankedCandidate",
    "VersionedRecipe",
    "branch_within_limits",
    "canonicalize_authorization_payload",
    "classify_risk",
    "compute_asset_id",
    "compute_authorization_digest",
    "compute_identity_digest",
    "decide_admission",
    "decide_execution_risk",
    "evaluate_action_risk",
    "get_recipe",
    "is_active_plan_asset_eligible",
    "list_recipes",
    "parse_asset_url",
    "rank_candidates",
    "resolve_recipe_ref",
    "select_next_branch",
    "transition_branch",
]
